### ISSUE TITLE
Unable To Generate Project Files After Adding Plugin

### ISSUE THREAD

**Issue by Derjyn** [getnamo/ZipUtility-ue4#14]
UBT will no longer generate project files after adding this plugin.

```
@progress 'Binding IntelliSense data...' 0%

ERROR: Unable to determine module type for ...\Engine\Plugins\Community\ZipUtility\Source\WindowsUtility\WindowsFileUtility.Build.cs
```

**Comment by getnamo** [comment]
Is this using the drag and drop v0.3.4 plugin found here https://github.com/getnamo/ZipUtility-ue4/releases/tag/0.3.4 ?

**Comment by getnamo** [comment]
Latest release doesn't appear to have this issue. Re-open with specific steps to reproduce if the issue persists.
