### ISSUE TITLE
Linking errors with C++ code

### ISSUE THREAD

**Issue by prisonerjohn** [getnamo/ZipUtility-ue4#25]
When I try to add the plugin and files to my C++ project, I get the following linking errors when compiling:
```
CompilerResultsLog: [1/1] Link UE4Editor-TestProject-7049.dll
CompilerResultsLog: Error: LINK : fatal error LNK1181: cannot open input file 'C:\Users\prisonerjohn\Desktop\TestProject\Plugins\ZipUtility-ue4\Intermediate\Build\Win64\UE4Editor\Development\UE4Editor-ZipUtility.lib'
CompilerResultsLog: ERROR: UBT ERROR: Failed to produce item: C:\Users\prisonerjohn\Desktop\TestProject\Binaries\Win64\UE4Editor-TestProject-7049.dll
```

I followed the instructions in the README to add the plugin, and tried restarting both Unreal Engine and Visual Studio.

Apologies if this isn't the best place to ask this, I'm still new to Unreal and not sure if this is due to a missing step in the installation instructions, or just an unrelated issue with how my project is set up.

**Comment by prisonerjohn** [comment]
Closing as I posted the same question on the UE forums, which seemed more appropriate: https://forums.unrealengine.com/development-discussion/engine-source-github/66762-plugin-ziputility-7zip?95022-Plugin-ZipUtility-(7zip)=

**Comment by getnamo** [comment]
Likely missing ats.lib link see https://github.com/getnamo/ZipUtility-ue4/blob/master/README.md#note-on-compiling
