### ISSUE TITLE
My editor crashes

### ISSUE THREAD

**Issue by Ashrindy** [getnamo/ZipUtility-ue4#37]
so i have it to unzip a file right at the start of the game but, the whole editor crashes and it says:

Assertion failed: O->GetClass()->ImplementsInterface(UZipUtilityInterface::StaticClass()) [File:C:/Users/Admin/Documents/GitHub/ZipUtilityWork/Plugins/ZipUtility-ue4/Intermediate/Build/Win64/UE4Editor/Inc/ZipUtility/ZipUtilityInterface.gen.cpp] [Line: 531]

UE4Editor_Core
UE4Editor_Core
UE4Editor_ZipUtility
UE4Editor_ZipUtility
UE4Editor_Core
UE4Editor_Core
UE4Editor_Core
UE4Editor_Engine
UE4Editor
UE4Editor
UE4Editor
UE4Editor
UE4Editor
kernel32
ntdll

**Comment by getnamo** [comment]
Your caller doesn't implement the required interface see https://github.com/getnamo/ZipUtility-ue4#blueprint-access second section where it talks about the interface

**Comment by Ashrindy** [comment]
> 
> 
> Your caller doesn't implement the required interface see https://github.com/getnamo/ZipUtility-ue4#blueprint-access second section where it talks about the interface

I've did that but crashed again with the same error.

**Comment by getnamo** [comment]
Version, language(bp/c++), platform, steps to reproduce

**Comment by Ashrindy** [comment]
> 
> 
> Version, language(bp/c++), platform, steps to reproduce

4.26, bp, windows, don't know what do you mean

**Comment by getnamo** [comment]
For bp show a screenshot of what you're calling and also class defaults section showing interface added to calling class

**Comment by getnamo** [comment]
Also what object type is doing the calls (uobject base? Actor? Game instance?)

**Comment by Ashrindy** [comment]
> 
> 
> Also what object type is doing the calls (uobject base? Actor? Game instance?)

![Screenshot_95](https://user-images.githubusercontent.com/47925123/116193350-8022d500-a72f-11eb-8ffc-61f8fb9be520.png)
![Screenshot_96](https://user-images.githubusercontent.com/47925123/116193354-80bb6b80-a72f-11eb-9d39-ce089a8707ed.png)

**Comment by getnamo** [comment]
Does your player character that you're passing into zip utility interface delegate have the zip utility interface? If not what are you trying to do with that reference?

**Comment by Ashrindy** [comment]
> 
> 
> Does your player character that you're passing into zip utility interface delegate have the zip utility interface? If not what are you trying to do with that reference?
> 
> If you're trying to listen to the progress, in the current blueprint, it needs a reference of 'self'

That worked! Thanks, I didn't also exactly knew what that Interface delegate meant.

**Comment by getnamo** [comment]
Great! It should be optional but if you do pass something to it in a call, it has to implement the interface
