### ISSUE TITLE
Editor crash (when called within widget)

### ISSUE THREAD

**Issue by rasapoisgone54** [getnamo/ZipUtility-ue4#38]
i have unzip in a widget and when its called the editor crashes and this is in the log
![Screenshot_97](https://user-images.githubusercontent.com/83280901/116227086-094c0300-a754-11eb-94fc-900c2e04af83.png)

**Comment by getnamo** [comment]
see potentially related: https://github.com/getnamo/ZipUtility-ue4/issues/37

**Comment by rasapoisgone54** [comment]
But i have the interface set, the same as #37

**Comment by getnamo** [comment]
Need more steps to reproduce, what are you calling? how? platform, version etc etc

**Comment by rasapoisgone54** [comment]
I'm calling it in a widget, platform windows, version 4.26,

This one is in the widget:
![Screenshot_98](https://user-images.githubusercontent.com/83280901/116306450-5c9a7180-a7a5-11eb-9687-df4cbe003b01.png)

And this one are the interfaces of the player:
![Screenshot_99](https://user-images.githubusercontent.com/83280901/116306452-5d330800-a7a5-11eb-9bbe-0b3598f768bd.png)

**Comment by rasapoisgone54** [comment]
Please someone respond :(

**Comment by getnamo** [comment]
Try again with passing self and implementing interface in calling actor

**Comment by rasapoisgone54** [comment]
So i've tried that right now but it just crashed again with the same error

> 
> 
> Try again with passing self and implementing interface in calling actor

**Comment by getnamo** [comment]
Try a different file e.g. regular zip at a know location, also try without any param reference in interface slot of the function call. Lambda / bg thread call error suggests content issue

**Comment by rasapoisgone54** [comment]
Nope crashed with the same error

> 
> 
> Try a different file e.g. regular zip at a know location, also try without any param reference in interface slot of the function call. Lambda / bg thread call error suggests content issue

**Comment by getnamo** [comment]
Keep in mind archive path should be absolute and you may need to convert it

**Comment by rasapoisgone54** [comment]
> 
> 
> Keep in mind archive path should be absolute and you may need to convert it

what do you mean by convert it?

**Comment by getnamo** [comment]
If you're passing a relative path (e.g. with ../ ) you will need to collapse it into an absolute path starting with e.g. C:/ etc

**Comment by rasapoisgone54** [comment]
> 
> 
> If you're passing a relative path (e.g. with ../ ) you will need to collapse it into an absolute path starting with e.g. C:/ etc

well that's what i've done!
![Screenshot_104](https://user-images.githubusercontent.com/83280901/116448309-43eb9380-a859-11eb-8abe-598b76f22867.png)

**Comment by rasapoisgone54** [comment]
Isn't it bcuz im calling in a widget?

**Comment by getnamo** [comment]
Your return value is it null or does it give you an object?

**Comment by getnamo** [comment]
Shouldn't be, but you can try outside the widget inside e.g. an actor

**Comment by rasapoisgone54** [comment]
> 
> 
> Your return value is it null or does it give you an object?

Can't know that bcuz the editor just instantly crashes

**Comment by rasapoisgone54** [comment]
> 
> 
> Shouldn't be, but you can try outside the widget inside e.g. an actor

Using it all the time outside of widget

**Comment by getnamo** [comment]
It works outside widget?

**Comment by rasapoisgone54** [comment]
Yes

**Comment by getnamo** [comment]
Then use it outside of a widget and forward the result to your widget. Unsure why this happens, maybe it's missing a world context to callbacks

**Comment by rasapoisgone54** [comment]
Like i tried to do function in the character and call the function in the widget but it was the same result

**Comment by getnamo** [comment]
Just tested a user widget with an interface, seems to work: 
![image](https://user-images.githubusercontent.com/542365/116449863-7b355280-a80f-11eb-8d0c-d1ec6a0e04b3.png)

![image](https://user-images.githubusercontent.com/542365/116449925-8f794f80-a80f-11eb-943b-703b3e6c7171.png)

Something else is going on; what are you doing differently vs when it does work for you?

**Comment by rasapoisgone54** [comment]
Nothing, just one is called in a map and the other one is called in a widget otherwise it's the same

**Comment by rasapoisgone54** [comment]
For some weird reason it started to work! I probably guess that converting .rar to .zip wasn't a good idea.
