### ISSUE TITLE
Unable to package project

### ISSUE THREAD

**Issue by RikoNee** [getnamo/ZipUtility-ue4#39]
Hi, i'm trying to package my project but i got an error:  
`D:\UE4\Project\Launcher\Plugins\ZipUtility\ThirdParty\7zpp\Include\7zpp.h(29): fatal error C1083: Impossible d'ouvrir le fichier include�: 'atlbase.h'�: No such file or directory`

I mean it can be this or another plugin but i've also this:
`UATHelper: Packaging (Windows (64-bit)):   ZipUtility Error: Couldn't find an ATLPath, fix it in ZipUtility.Build.cs
UATHelper: Packaging (Windows (64-bit)):   D:\UE4\Project\Launcher\Plugins\ZipUtility\Source\ZipUtility\ZipUtility.Build.cs: warning: Referenced directory 'D:\UE4\Project\Launcher\Plugins\ZipUtility\Source\include' does not exist.
PackagingResults: Error: can't find VS path: System.IO.DirectoryNotFoundException: Impossible de trouver une partie du chemin d'accès 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC'.
PackagingResults: Error: Couldn't find an ATLPath, fix it in ZipUtility.Build.cs
PackagingResults: Warning: Referenced directory 'D:\UE4\Project\Launcher\Plugins\ZipUtility\Source\include' does not exist`

So if u can help me

**Comment by getnamo** [comment]
see https://github.com/getnamo/ZipUtility-ue4#note-on-compiling

**Comment by RikoNee** [comment]
I see it and i have 3 different VSC, i think it's VSC build tool so if u can tell me please

**Comment by RikoNee** [comment]
Okey i found, it was VSC 2017 so i close this issue, all work fine.
