### ISSUE TITLE
Not working in a packaged game

### ISSUE THREAD

**Issue by devigba916** [getnamo/ZipUtility-ue4#40]
So I packaged my game and the function for unzip are just not working. I have UE4 4.26, bp, Windows.

**Comment by getnamo** [comment]
Check your path, packaged games may have different paths than editor ones

**Comment by devigba916** [comment]
> 
> 
> Check your path, packaged games may have different paths than editor ones

i've set the path to be always where the project directory is

**Comment by getnamo** [comment]
Just tested a packaged build it works as expected. Most unzip/zip commands require absolute paths

**Comment by devigba916** [comment]
> 
> 
> Just tested a packaged build it works as expected. Most unzip/zip commands require absolute paths

I have those

**Comment by devigba916** [comment]
Just figgured it out my antivirus was stupid and didn't let the game to do it.
