### ISSUE TITLE
I can't package my game

### ISSUE THREAD

**Issue by liLaur** [getnamo/ZipUtility-ue4#44]
I get this error at ZipUtility plugin
![unknown](https://user-images.githubusercontent.com/63873233/130462155-8033c23f-060c-46cc-ab01-054c8960a96e.png)

**Comment by getnamo** [comment]
https://github.com/getnamo/ZipUtility-ue4#note-on-compiling

**Comment by liLaur** [comment]
I had to install Visual Studio 2017 to work
