### ISSUE TITLE
Wrong initializer list of Tarray in ZipFileFunctionInternalCallback.cpp at line 17

### ISSUE THREAD

**Issue by RPG3D** [getnamo/ZipUtility-ue4#7]
https://answers.unrealengine.com/questions/183185/tarray-initialization.html
`TArray<int32> FileIndices;
int32 intArray[] = { FileIndex };
FileIndices.Append(intArray, ARRAY_COUNT(intArray));`

**Comment by getnamo** [comment]
is this line causing a crash? Does it impact a single VS version or multiple?

More data about the issue could be useful
