### ISSUE TITLE
Crash in packaged game.

### ISSUE THREAD

**Issue by koikw** [getnamo/ZipUtility-ue4#9]
Just log..
```
Error: === Critical error: ===
Fatal error!
```
And in editor mode it wroks well.
WIndows 10
UE4.12.5

**Comment by getnamo** [comment]
Might need more information than that, what were you doing when it crashed? do you have a minimal project that can reproduce the problem?

**Comment by koikw** [comment]
Here is my simple project, I think the problem happend at add zip interface in blueprint.
[Simple project download](https://www.dropbox.com/s/gfcmpzxozgx6h3e/SimpleUnzip.zip?dl=0)

**Comment by getnamo** [comment]
I've update to 4.15 and tried to package the project, it's still not working yet and I'll need to find more time to get packaging to work for this plugin. Thanks for the example project for testing.

**Comment by getnamo** [comment]
Try this update: https://github.com/getnamo/ZipUtility-ue4/releases/tag/0.3.1 and let me know if it fixes things

**Comment by koikw** [comment]
I had try this new version in 4.15, it looks fixed. ^ ^
But in 4.12 packaged game is still crash.
Anyway thanks.

**Comment by getnamo** [comment]
While I never back port releases, you should be able to take the code changes I made for 4.15 and recompile for 4.12.

**Comment by getnamo** [comment]
closing issue, post if you get problems in the future
